import type { RequirementShareSummary, RequirementTemplate } from './api/types';

export const ONBOARDING_DISMISSED_KEY = 'haao-onboarding-dismissed';

export const HELP_TOOLTIPS = {
  tech_lead:
    'Cloud reasoner that decomposes plain-language requirements into atomic tickets and audits finished work.',
  gatekeeper:
    'Fast local model that triages logs and pre-checks definition-of-done before tickets move forward.',
  escalation:
    'When local retry budget is exhausted, the orchestrator reassigns the ticket to the Tech Lead model.',
  backlog_proposal:
    'Proposed tickets from Tech Lead — approve them to move to Ready before agents run.',
  ready_column:
    'Approved tickets wait here; auto-run picks them up for execution.',
  cloud_vs_local:
    'Local models run code in your repo; cloud models handle reasoning, audit, and escalation.',
  chat_proposal:
    'Agent-filed work stays in Backlog as a proposal until you approve it.',
} as const;

export const MOCK_REQUIREMENT_TEMPLATES: RequirementTemplate[] = [
  {
    id: 'builtin-add-endpoint',
    title: 'Add an API endpoint',
    prompt: 'Add a small API endpoint for the requested resource, including validation and tests.',
    scope_paths: [],
    constraints: ['Keep the endpoint narrow and consistent with existing API patterns.'],
    built_in: true,
  },
  {
    id: 'builtin-fix-failing-test',
    title: 'Fix a failing test',
    prompt: 'Investigate the failing test, identify the root cause, and make the minimal code change to pass it.',
    scope_paths: [],
    constraints: ['Do not weaken or delete the failing test unless it is demonstrably invalid.'],
    built_in: true,
  },
  {
    id: 'builtin-refactor-small',
    title: 'Small refactor',
    prompt: 'Refactor the selected code for clarity while preserving behavior.',
    scope_paths: [],
    constraints: ['Keep public APIs stable and add or update tests only when behavior is clarified.'],
    built_in: true,
  },
  {
    id: 'builtin-add-observability',
    title: 'Add observability',
    prompt: 'Add useful logging or run-event instrumentation around this workflow.',
    scope_paths: [],
    constraints: ['Redact secrets and avoid noisy logs in hot paths.'],
    built_in: true,
  },
];

export function summaryToMarkdown(summary: RequirementShareSummary): string {
  const lines: string[] = [
    `# Requirement ${summary.requirement.id}`,
    '',
    `**Project:** ${summary.requirement.project_id}`,
    `**Status:** ${summary.requirement.status}`,
    '',
    '## Prompt',
    summary.requirement.prompt,
    '',
  ];

  if (summary.requirement.scope_paths?.length) {
    lines.push('## Scope', ...summary.requirement.scope_paths.map((path) => `- \`${path}\``), '');
  }
  if (summary.requirement.constraints?.length) {
    lines.push('## Constraints', ...summary.requirement.constraints.map((item) => `- ${item}`), '');
  }
  if (summary.requirement.acceptance_notes) {
    lines.push('## Acceptance notes', summary.requirement.acceptance_notes, '');
  }

  if (summary.tickets.length > 0) {
    lines.push('## Tickets');
    for (const ticket of summary.tickets) {
      lines.push(`### ${ticket.id} — ${ticket.title}`, `- Status: ${ticket.status}`);
      if (ticket.outcome) lines.push(`- Outcome: ${ticket.outcome}`);
      if (ticket.diff) {
        lines.push('', '```diff', ticket.diff, '```', '');
      }
    }
    lines.push('');
  }

  if (summary.cost) {
    lines.push(
      '## Cost',
      `- Total (USD): ${summary.cost.total_usd?.toFixed(4) ?? '0.0000'}`,
      `- Cloud requirement: ${summary.cost.requirement_usd?.toFixed(4) ?? '0.0000'}`,
      `- Run events: ${summary.cost.run_events_usd?.toFixed(4) ?? '0.0000'}`,
      '',
    );
  }

  lines.push('_Redacted share summary generated by HAAO._');
  return lines.join('\n');
}

export function summaryApiUrl(requirementId: string): string {
  const base = typeof window !== 'undefined' ? window.location.origin : '';
  return `${base}/api/requirements/${encodeURIComponent(requirementId)}/summary`;
}
